spring:
  datasource:
   username: myboot
   password: 123456
   url: jdbc:mysql://192.168.1.248:3306/myboot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
   driver-class-name: com.mysql.cj.jdbc.Driver

